apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "p9-app.fullname" . }}
  labels:
    {{- include "p9-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "p9-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "p9-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: p9-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
